
CREATE TABLE ETUDE (
     ID INT NOT NULL primary key AUTO_INCREMENT,
	 ACTIVE  boolean NOT NULL,
	 STATUT_ETUDE VARCHAR(50) NULL DEFAULT NULL,
	 ETAT_ETUDE VARCHAR(50) NULL DEFAULT NULL,
	 COMMENTAIRE  VARCHAR(50) NULL DEFAULT NULL,
	 DATE_EVALUATION  DATE  NULL DEFAULT NULL,
	 DATE_VALIDATION  DATE NULL DEFAULT NULL,
	 DATE_FINALISATION  DATE NULL DEFAULT NULL
);

CREATE TABLE ECHANTILLON (
    ID INT  NOT NULL primary key AUTO_INCREMENT,
    NOMBRE_MINIMUM INT NULL DEFAULT NULL,
    TAUX_SONDAGE INT NULL DEFAULT NULL,
	ETUDE_ID INT NULL DEFAULT NULL
);


CREATE TABLE FICHE_PERSONNE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ACTIVE boolean NOT NULL default true ,
    NUMERO INT NULL DEFAULT NULL,
    NOM varchar(10),
    PRENOM varchar(10),
    AGE INT NULL DEFAULT NULL,
    SEXE VARCHAR(50) NULL DEFAULT NULL,
    CONTEXTE_PSYCHOLOGIQUE VARCHAR(50) NULL DEFAULT NULL,
	ETUDE_ID INT NULL DEFAULT NULL,
	ECHANTILLON_ID INT NULL DEFAULT NULL
	
	
);

ALTER TABLE ECHANTILLON
 ADD CONSTRAINT FK_Echantillon_ETUDE_ID FOREIGN KEY (ETUDE_ID) REFERENCES ETUDE (ID);
 
ALTER TABLE FICHE_PERSONNE
 ADD CONSTRAINT FK_FichePersonne_ETUDE_ID FOREIGN KEY (ETUDE_ID) REFERENCES ETUDE (ID);
 
 ALTER TABLE FICHE_PERSONNE
 ADD CONSTRAINT FK_ECHANTILLON_ID FOREIGN KEY (ECHANTILLON_ID) REFERENCES ECHANTILLON (ID);
